package server

import pb "fashion-grpc/proto"

// mockProducts is a fixed, in-memory catalog. In a real service this would
// come from a database.
var mockProducts = []*pb.Product{
	{
		Id:       "p1",
		Name:     "Classic Crew T-Shirt",
		Category: "t-shirt",
		Brand:    "Northline",
		Price:    19.99,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L", "XL"},
		Color:    "0xFF3F51B5",
	},
	{
		Id:       "p2",
		Name:     "Merino Wool Pullover",
		Category: "pullover",
		Brand:    "Alderwood",
		Price:    59.50,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L"},
		Color:    "0xFF8D6E63",
	},
	{
		Id:       "p3",
		Name:     "Wrap Midi Dress",
		Category: "dress",
		Brand:    "Solaya",
		Price:    74.00,
		Currency: "EUR",
		Sizes:    []string{"XS", "S", "M"},
		Color:    "0xFFE91E63",
	},
	{
		Id:       "p4",
		Name:     "Slim Fit Jeans",
		Category: "jeans",
		Brand:    "Northline",
		Price:    49.90,
		Currency: "EUR",
		Sizes:    []string{"28", "30", "32", "34"},
		Color:    "0xFF455A64",
	},
	{
		Id:       "p5",
		Name:     "Oversized Hoodie",
		Category: "hoodie",
		Brand:    "Alderwood",
		Price:    64.90,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L", "XL"},
		Color:    "0xFF009688",
	},
	{
		Id:       "p6",
		Name:     "Pleated Midi Skirt",
		Category: "skirt",
		Brand:    "Solaya",
		Price:    44.00,
		Currency: "EUR",
		Sizes:    []string{"XS", "S", "M", "L"},
		Color:    "0xFFFFC107",
	},
	{
		Id:       "p7",
		Name:     "Tailored Blazer",
		Category: "blazer",
		Brand:    "Northline",
		Price:    129.00,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L"},
		Color:    "0xFF212121",
	},
	{
		Id:       "p8",
		Name:     "Linen Shorts",
		Category: "shorts",
		Brand:    "Solaya",
		Price:    34.50,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L", "XL"},
		Color:    "0xFF03A9F4",
	},
	{
		Id:       "p9",
		Name:     "Denim Jacket",
		Category: "jacket",
		Brand:    "Northline",
		Price:    89.00,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L", "XL"},
		Color:    "0xFF1976D2",
	},
	{
		Id:       "p10",
		Name:     "Cable Knit Sweater",
		Category: "sweater",
		Brand:    "Alderwood",
		Price:    69.90,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L"},
		Color:    "0xFF6D4C41",
	},
	{
		Id:       "p11",
		Name:     "Silk Slip Dress",
		Category: "dress",
		Brand:    "Solaya",
		Price:    98.00,
		Currency: "EUR",
		Sizes:    []string{"XS", "S", "M"},
		Color:    "0xFF9C27B0",
	},
	{
		Id:       "p12",
		Name:     "Cargo Trousers",
		Category: "trousers",
		Brand:    "Northline",
		Price:    54.90,
		Currency: "EUR",
		Sizes:    []string{"30", "32", "34", "36"},
		Color:    "0xFF33691E",
	},
	{
		Id:       "p13",
		Name:     "Ribbed Tank Top",
		Category: "tank-top",
		Brand:    "Alderwood",
		Price:    17.50,
		Currency: "EUR",
		Sizes:    []string{"XS", "S", "M", "L"},
		Color:    "0xFFF06292",
	},
	{
		Id:       "p14",
		Name:     "Quilted Puffer Coat",
		Category: "coat",
		Brand:    "Solaya",
		Price:    159.00,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L", "XL"},
		Color:    "0xFF37474F",
	},
	{
		Id:       "p15",
		Name:     "Chino Shorts",
		Category: "shorts",
		Brand:    "Northline",
		Price:    32.00,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L"},
		Color:    "0xFFCDDC39",
	},
	{
		Id:       "p16",
		Name:     "Cashmere Scarf",
		Category: "accessory",
		Brand:    "Alderwood",
		Price:    39.90,
		Currency: "EUR",
		Sizes:    []string{"One Size"},
		Color:    "0xFF800000",
	},
	{
		Id:       "p17",
		Name:     "Floral Maxi Dress",
		Category: "dress",
		Brand:    "Solaya",
		Price:    84.00,
		Currency: "EUR",
		Sizes:    []string{"XS", "S", "M", "L"},
		Color:    "0xFFFF5722",
	},
	{
		Id:       "p18",
		Name:     "Straight Leg Jeans",
		Category: "jeans",
		Brand:    "Northline",
		Price:    52.00,
		Currency: "EUR",
		Sizes:    []string{"28", "30", "32", "34", "36"},
		Color:    "0xFF00BCD4",
	},
	{
		Id:       "p19",
		Name:     "Zip-Up Track Jacket",
		Category: "jacket",
		Brand:    "Alderwood",
		Price:    58.00,
		Currency: "EUR",
		Sizes:    []string{"S", "M", "L", "XL"},
		Color:    "0xFF7B1FA2",
	},
	{
		Id:       "p20",
		Name:     "Leather Ankle Boots",
		Category: "footwear",
		Brand:    "Solaya",
		Price:    139.00,
		Currency: "EUR",
		Sizes:    []string{"37", "38", "39", "40", "41"},
		Color:    "0xFF5D4037",
	},
}
